default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: feedscraper_development

test:
  <<: *default
  database: feedscraper_test

production:
  <<: *default
  database: feedscraper_production
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
